# Generated by Django 5.0.6 on 2024-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=10, verbose_name='Kamera raqami')),
                ('created', models.DateTimeField(verbose_name='Sana vaqt')),
                ('number_of_people', models.IntegerField(verbose_name='Odamlar soni')),
                ('image', models.ImageField(upload_to='images/group', verbose_name='Rasm')),
                ('type', models.CharField(choices=[('input', 'Kirish'), ('output', 'Chiqish'), ('group_input', "Guruh bo'lib kirish")], max_length=20, verbose_name='Holati')),
            ],
        ),
    ]
